build.gradle, src/main/java/com/sinabro/server/config/SwaggerConfig.java, src/main/java/com/sinabro/server/controller/PlacesController.java, src/main/java/com/sinabro/server/model/places/Places.java, src/main/resources/application.yml
resolve #2 
앞으로 추가될 API들을 Swagger를 통해 문서화하여 보다 관리하기
용이하도록 해당 프레임워크를 추가하였습니다.
- 서버 내 Swagger 적용
- Swagger-ui 페이지 내에서 기존 `장소 관련 API` 스펙을 확인할 수 있도록
일부 annotation을 추가하였습니다.
> 로컬 환경 swagger-ui 주소 : **http://localhost:9000/swagger-ui/index.html**
- `Swagger3.0` 추가 후
=> [feat]: Rest API 문서화를 위한 Swagger 3.0 프레임워크 추가 (#2)

src/main/resources/application.yml
resolve #6 
기존 `goormIDE`에서 서비스 중이던 MySQL의 포트포워딩 정보가
변경되어 서버와의 상호 통신 에러가 발생해 변경된 Hostname 및 Port값으로
수정하고자 하였습니다.
- `application.yml` 파일 내 MySQL url 수정
- 현재 `application.yml` 파일이 깃 이력에 포함되어 있는데, DB 접근에 대한 보안 이슈가
발생할 수도 있을 것 같아 추후에 배포 전용 브랜치를 마련하도록 하겠습니다.
=> [fix]: MySQL 포트포워딩으로 인한 Hostname/Port 값 변경 (#6)

models/place.js
resolve #13 
Place 스키마에 대한 `insert` 명령 수행 시 스키마의 버전을 추적하기 위해 자동으로 추가되는
`__v` 필드를 생성되지 않도록 `versionKey` 생성 속성을 비활성화하였습니다.
- `Place` 스키마의 `versionKey` 생성 속성을 비활성화 한다.
- `versionKey` 생성 속성의 비활성화 상태(`versionKey`가 생성되지 않음)
=> [fix]: Place 스키마 versionKey 비활성화 (#13)

routes/places.js
resolve #24 
기존 `장소 정보 삭제` API 요청 시 응답으로 동일한 위치에 해당하는
장소에 대하여 잔여 장소의 수를 `response body`로 client 측에 응답해
주게 되는데, 이때 `http status code`를 `204`로 응답하였을 경우
`response body`에 담긴 데이터는 누락되는 문제가 있어 `200`으로 값을
수정하였고, `장소 정보 등록` API 요청 후 `place` object에 대한 값만
body로 보내어 client 측과 데이터 규격을 맞출 수 있도록 코드를 수정하였습니다.
- `장소 정보 삭제` API response `http status code` 변경
> `http status code` 변경으로 인한 `swagger` 문서 수정
- `장소 정보 등록` API `response body` 데이터 변경
없습니다
=> [fix]: 장소 정보 삭제 API response http status code 및 장소 정보 등록 API response body 데이터 변경 (#24)

routes/middlewares/authorization.js, routes/people_numbers.js, routes/places.js
resolve #28 
#26 이슈 작업을 통해 현재 서버 측에서 다양한 APIs를 사용할 때 `비회원`인 경우
특정 APIs 사용에 제한둘 수 있도록 하고자 JWT access token의 유효성
검증 middleware를 서버 APIs에 부분적으로 적용하였습니다.
- `people_numbers` route 내 일부 APIs에 대하여 access token 유효성 검증 middleware 적용
- `places` route 내 일부 APIs에 대하여 access token 유효성 검증 middleware 적용
없습니다
=> [fix]: `JWT` 도입으로 인한 기존 APIs 사용 전 토큰 유효성 인증이 필요 부분들에 대한 검증 단계 추가 (#28)

models/marker.js, models/people_number.js, models/place.js
resolve #30 
현재 DB 내에서 사용 중인 모든 `Schema`에 대하여 `versionKey` 생성 옵션이
비활성화 되어 있는데, 해당 옵션을 일괄적으로 허용하여 데이터의 일관성 문제가
나타나지 않도록 하였습니다.
- `markers` Schema에 대한 `versionKey` 옵션 생성 허용
- `people_numbers` Schema에 대한 `versionKey` 옵션 생성 허용
- `places` Schema에 대한 `versionKey` 옵션 생성 허용
없습니다
=> [fix]: DB 내 모든 Schema에 대하여 versionKey 생성 옵션 허용 (#30)

routes/auth.js, routes/middlewares/authorization.js, server.js
resolve #35 
#26 이슈 작업으로 인해 추가된 `로그인/회원가입` APIs에 대한
문서화를 수행하였습니다.
- `로그인` API에 대한 `swagger-doc` 추가
- `회원가입` API에 대한 `swagger-doc` 추가
- `JWT(Json Web Token)` **verifying** middleware 내에 `clientToken`값 저장 로직 수정
- `JWT` 추가에 따른 `swaggerOptions` 내 JWT 이용에 대한 `securityDefinitions` 속성 추가
- #33 이슈 작업 중 누락된 작업 사항 커밋
> `people_numbers` collection name 변경으로 인한 router 엔드포인트 path 변경(`/api/peopleNumbers` -> `/api/headcounts`')
- JWT 사용을 위한 `Authorize` 기능 활성화
=> [feat]: 로그인/회원가입 APIs에 대한 swagger-doc 문서화 (#35)

routes/auth.js
resolve #39 
애플리케이션 내에서 회원가입 1단계 중 사용자가 사용할 이메일을
입력하는 부분이 있는데, 해당 이메일은 현재 시스템에서 개별 회원의
고유한 아이디로써 사용되는 정보이기에 사용자는 사용하려는 이메일에 한하여
반드시 중복확인이 이뤄질 수 있도록 하고자 `이메일 중복 확인` API를 추가하고자
하였습니다.
- `auth` router 내에 `이메일 중복 확인` API 추가
- `이메일 중복 확인` API에 대한 `swagger-doc` 추가는 추후에 진행하도록 하겠습니다
=> [feat]: 'auth' router 내에 '이메일 중복 확인' API 추가 (#39)

routes/auth.js
resolve #41 
클라이언트 측에서 #39 이슈 작업을 통해 추가된 `이메일 중복 확인` API 사용 시
`이메일 형식 유효성 검증` 및 `이미 존재하는 이메일 확인`에 대한 `http status code`가
동일하여 상호 구분성이 다소 모호할 수 있다는 문제점이 있어 `이미 존재하는 이메일 확인`의
경우에 대한 http status code를 기존 400에서 409로 변경하였습니다.
- `이메일 중복 확인` API 내 `이미 존재하는 이메일 확인`에 대한 http status code를 기존 `400`에서 `409`으로 변경
- `이메일 중복 확인` API 요청 성공 시 status code 200과 함께 반환되는 response body content 메시지 변경
없습니다
=> [fix]: 이메일 중복 확인 API http status code 및 response body content 변경 (#41)

routes/auth.js
resolve #47 
#39 이슈 작업을 통해 서버에 추가된 `이메일 중복 확인` API에 대한
swagger-doc을 추가하였습니다.
- `/api/auth/public/search` => 이메일 중복 확인 API에 대한 swagger-doc 문서화
- `이메일 중복 확인` API에 대한 swagger-doc 화면
=> [feat]: 이메일 중복 확인 API에 대한 swagger-doc 문서화 (#47)

routes/places.js, routes/users.js
resolve #50 
`신규 장소 등록` API를 사용하려면 request body에 문자열형으로
latitude(위도), longitude(경도) 값을 넘겨줘야 하는데, 실제 API
구성 코드 내에 `Bad Request(400)`를 판단하는 조건문에서 request body에
담긴 위도, 경도 값이 숫자형(number)이 아닐 때 참이라는 조건으로 구성되어 있어
`문자열형`으로 넘어온 해당 두 값들에 의하여 `Bad Request(400)` 에러가 발생하여
해당 문제를 수정하였습니다.
- `신규 장소 등록` API 내에 `Bad Request(400)` 판단 조건문 중
latitude, longitude 판단 조건식 수정
- `users` router 내에 불필요 `console.log` 함수 사용 코드 라인 제거
없습니다
=> [fix]: 신규 장소 등록 API Bad Request(400) 검증 로직 수정 (#50)

routes/auth.js, routes/headcounts.js, routes/markers.js, routes/places.js, routes/users.js
resolve #52 
클라이언트 측 애플리케이션 내에서 사용자가 `마이페이지` 액티비티 내에서
원하는 경우 본인의 계정 비밀번호를 새롭게 변경할 수 있도록 하는 `비밀번호 변경`
API를 추가하였습니다.
- `비밀번호 변경` API 및 `swagger-doc` 추가
- http status code 500에 대한 error 메시지 속성 정정
- 일부 APIs `http request body`에 대한 object destructuring 적용
- `장소 정보 업데이트` API에 대한 `http method` 변경
> (기존) `PATCH` → (변경 후) `PUT`)
- `비밀번호 변경` API에 대한 swagger-doc 화면
=> [feat]: 비밀번호 변경 API 추가 (#52)

routes/places.js
resolve #56 
기존 `장소 정보 수정` API의 경우 `Bad Request`에 대한 검증 단계가 존재하지 않았고,
`res.place` 값을 설정하는 부분의 로직이 의도하지 않은 방향으로 작동되는 버그가 있었기
때문에 해당 문제들을 해결하였습니다.
- `places` router` 내 `장소 정보 수정` API 로직 수정
없습니다
=> [fix]: '장소 정보 수정' API 오류 수정 (#56)

routes/users.js
resolve #58 
기존 `회원 정보 수정/비밀번호 변경` APIs에서 사용 중이던 `response.body` 내 요구 속성들에 대해서
일부 수정하였습니다.
- `회원 정보 수정` API `response body` 내 요구 속성명 변경
> newPassword -> password
- `비밀번호 변경` API `response body` 내 요구 속성명 변경
> newUsername -> username, newEmail -> mail
없습니다
=> [fix]: '회원 정보 수정/비밀번호 변경' APIs response.body 내 요구 속성명 변경 (#58)

models/bookmark.js, routes/auth.js, routes/bookmarks.js, routes/headcounts.js, routes/markers.js, routes/places.js, routes/users.js, server.js
resolve #45 
클라이언트 애플리케이션 내에 사용자가 특정 장소에 대하여 즐겨찾기 기능을
사용할 수 있도록 개발된 만큼 서버 측에서도 해당 기능을 실제로 이용 할 수 있도록 
관련 APIs(즐겨찾기 리스트 `생성/조회/삭제/수정`)를 추가하였습니다.
- DB 내 `bookmarks` collection 추가
- `bookmarks`에 대한 model 및 route 추가
- `즐겨찾기 리스트` (생성/조회/삭제/수정)에 대한 APIs 추가
- 타 route 파일 내 일부 변수 상수화
- 일부 APIs response 코드에 대한 return문 추가
없습니다
=> [feat]: 즐겨찾기 리스트 관련 APIs 추가 (#45)

routes/auth.js, routes/headcounts.js, routes/markers.js, routes/middlewares/authorization.js, routes/places.js, routes/users.js
resolve #65 
현재 서버 측에 추가된 여러 API 구성 코드 중에서 동일 동작에 대해 `try-catch` 구문이
중첩 혹은 여럿으로 나뉘어 쓰이는 부분들을 하나로 간략화하여 코드의 가독성을 향상시키고자
하였고, 그에 따라 변수로 사용되던 일부 데이터들에 대하여 상수화를 진행하고자 하였습니다.
추가적으로, 현재까지 추가된 APIs 스펙에 대해 `swagger-doc` 상호 간에 일치하지 않는
부분들이 확인되어 해당 부분까지 함께 정정하였습니다.
- `auth, headcounts, markers, places, users` 라우터 코드
없습니다
=> [refactor]: 다중 try-catch 구문 간략화 및 swagger-doc 문서 정정 (#65)

routes/bookmarks.js, routes/headcounts.js
resolve #71 
기존 `headcounts` 라우터 코드 중 인자로 들어온 배열의 각 요소인 Object에
`updateElapsedTime` 속성을 기준에 맞게 추가하는 `addUpdateElapsedTimeProp`
미들웨어가 있었는데, 클라이언트 측에서 애플리케이션 실행 후 카카오맵을 처음 확인하게
되었을 때 동일한 위도, 경도를 가리키는 장소에 대해서 복수의 마커가 생성되는 문제가 있어
동일한 위치를 가리키는 장소는 하나의 마커로 그룹화 될 수 있게끔 하고자 해당 기능을 수행하는
미들웨어를 추가하였습니다.
- `filterAndSortByCreatedTime` 미들웨어 추가
> 동일한 위치를 가리키는 장소를 하나의 마커로 그룹화한 후 최신 `createdTime` 값을 지닌 Object를
기준으로 정렬 기능 수행
> `getPlacesInformations` 미들웨어 설명 주석 본문 수정
없습니다
=> [feat]: filterAndSortByCreatedTime 미들웨어 추가 (#71)

models/headcount.js, routes/headcounts.js
resolve #77 
`특정 장소에 대한 인원수 등록` API 사용 시 인원수 정보를 등록한 사용자의
정보를 알 수 있도록 하고자 `headcounts` collection model에 대해서 `userId` 속성을
추가하고자 하였고, 기존 `headcounts` 라우터 내 미사용 API에 대해서 이를 제거하고,
`특정 마커 위치에 대한 장소 정보 및 인원수 세부 정보 반환 API`, `getPlaceInformations`
미들웨어를 수정하였습니다.
- `headcounts` collection model에 대해 `userId` 속성 추가
- `headcounts` 라우터 내 미사용 API 제거
- `특정 마커 위치에 대한 장소 정보 및 인원수 세부 정보 반환 API` 로직 수정
- `getPlaceInformations` 미들웨어 수정
- 기존 `headcounts` collection model 구조
- `userId` 속성 추가 후 `headcounts` collection model 구조
=> [fix]: headcounts 라우터 내 미사용 API 코드 제거 및 특정 마커 위치에 대한 장소 정보 및 인원수 세부 정보 반환 API, getPlaceInformations 미들웨어 수정 (#77)

routes/places.js
resolve #81 
`신규 장소 등록` API 사용으로 인해 `headcounts` collection 내에 신규
document가 추가될 때 `userId`도 함께 기록될 수 있도록 하기 위해
`신규 장소 등록` API의 로직을 수정하였습니다.
- `신규 장소 등록` API 로직 수정
없습니다
=> [fix]: '신규 장소 등록' API 로직 수정 (#81)

routes/headcounts.js
resolve #83 
`addUpdateElapsedTimeProp` 미들웨어 코드 중
`elapsedTime(장소 추가 후 현재까지 경과시간)` 값을 구하는 로직 내
문제가 있어 올바르게 수정하였습니다.
- `headcounts` 라우터 내 `addUpdateElapsedTimeProp` 미들웨어 `elapsedTime` 로직 수정
없습니다
=> [fix]: 'addUpdateElapsedTimeProp' 미들웨어 로직 수정 (#83)

routes/bookmarks.js
resolve #91 
기존 `특정 장소의 즐겨찾기 여부 확인` API를 클라이언트 애플리케이션 상황에
맞게 변경하고자 기존 API 로직 및 스펙을 변경하였습니다.
- `특정 장소의 즐겨찾기 여부 확인` API 스펙 변경
> API명, 로직, 스펙(응답 데이터) 변경
없습니다
=> [fix]: '특정 장소의 즐겨찾기 여부 확인' API 스펙 변경 (#91)

package-lock.json, package.json, routes/users.js
resolve #101 
사용자가 회원가입한 계정의 비밀번호를 기억하지 못 할 때
가입 메일로 임시 비밀번호를 전송하여 회원 정보를 찾을 수 있도록
하는 기능을 추가하였습니다.
- `임시 비밀번호 생성` API 추가
> <picture>
>   <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/light-theme/note.svg">
>   <img alt="Note" src="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/dark-theme/note.svg">
> </picture><br>
> Note (`users` collection 관련 APIs)
1. _**[POST]**_ **`/user/generate-temp-password`** API 추가 **➔** 회원의 기존 비밀번호 대신 임시 비밀번호로 변경되며, 요청된 이메일 주소로 임시 비밀번호를 발송합니다.
- `임시 비밀번호 생성` API 사용 후
>  요청 메일 주소로 임시 비밀번호가 발송된 메일 화면
=> [feat]: `임시 비밀번호 생성` API 추가 (#101)

models/bookmark.js, models/searchHistory.js, routes/bookmarks.js, routes/headcounts.js, routes/markers.js, routes/places.js, routes/searchHistories.js, routes/users.js, server.js
resolve #105 
애플리케이션 내에서 회원 사용자가 특정 장소명을 키워드로 사용하여
장소 검색 시 이에 대한 기록을 남길 수 있도록 `장소 검색 정보` 조회/등록/삭제
API를 일괄적으로 추가하였습니다.
> <picture>
>   <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/light-theme/note.svg">
>   <img alt="Note" src="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/dark-theme/note.svg">
> </picture><br>
> Note (`users` collection 관련 APIs)
1. _**[GET]**_ **`/search-histories/private`** API 추가 **➔** (search_history) collection 내에서 사용자가 검색하여 선택했던 장소 목록을 반환합니다.
2. _**[POST]**_ **`/search-histories/private`** API 추가 **➔** 사용자가 검색 후 선택한 장소 정보를 등록합니다.
3. _**[DELETE]**_ **`/search-histories/private/{searchHistoryId}`** API 추가 **➔** 사용자가 검색 후 선택하여 저장된 장소 정보 기록을 제거합니다.
- …
=> [feat]: `장소 검색 기록 관련` APIs 추가 (#105)

models/searchHistory.js, routes/searchHistories.js
resolve #107 
`search_history` collection 내에서 조회되는 데이터를 현재 년도 기준으로만
필터링할 수 있도록 기존 스키마에 `createdTime` 속성을 추가하였습니다.
- `search_history` collection에 대한 스키마 모델 파일 내 `createdTime` 속성 추가
- `검색하여 선택했던 장소 목록 반환` API 구성 코드 내 `createdTime` 속성 추가 및 작년
document(s) 삭제 로직 추가
없습니다
=> [fix]: search_history collection 스키마 내 createdTime 속성 추가 (#107)

routes/searchHistories.js
resolve #110 
기존 `검색하여 선택했던 장소 목록 반환` API 사용 시 데이터 조회 순서는
`search_history` collection에 추가된 document들의 순서대로 조회되었는데,
`createdTime` 속성의 값이 최신인 데이터들부터 조회되도록 관련 로직을 추가하였습니다.
- `검색하여 선택했던 장소 목록 반환` API 내에 데이터 조회 정렬 순서 변경 로직 추가
없습니다
=> [fix]: '검색하여 선택했던 장소 목록 반환' API 데이터 조회 순서 변경 (#110)

models/headcount.js, models/userWithdrawalReasons.js, routes/auth.js, routes/headcounts.js, routes/places.js
resolve #109
회원가입한 회원이 서비스에서 본인의 정보를 원하는 때에 지울 수 있도록
하고자 `회원 탈퇴 및 사유 기록` API를 추가하였습니다.
- `회원 탈퇴 및 사유 기록` API 추가
> <picture>
>   <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/light-theme/note.svg">
>   <img alt="Note" src="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/dark-theme/note.svg">
> </picture><br>
> Note (`users/user_withdrawal_reasons` collection 관련 APIs)
1. _**[POST]**_ **`/api/auth/private/delete-account`** API 추가 **➔** 인증된 사용자의 계정을 삭제하며, 사유를 기록합니다.
- `회원 탈퇴 및 사유 기록` API에 대한 **swagger-doc**
- 추가된 `user_withdrawal_reasons` collection에 대한 스키마 모델 파일 구조
=> [feat]: `회원 탈퇴 및 사유 기록` API 추가 (#109)

server.js
resolve #113 
httpLogger 내에서 `error.log`에 대한 내용을 별도로 처리하지 않도록
하고자 관련 코드를 제거하였습니다.
- httpLogger 내에 `error.log` 제거
없습니다
=> [fix]: httpLogger 내에 'error.log' 제거 (#113)

models/user_info.js, routes/auth.js, routes/users.js
resolve #115 
기존 `user_infos` collection 내에 **회원가입**에 의해 신규 유저 정보가
추가되면, 해당 유저가 언제 가입했는지 확인하기 위해 서버 로그를 살펴봐야
하는 번거로움이 있어서 `createdTime` 속성을 추가하여 쉽게 파악할 수
있도록 하였습니다.
- `user_infos` collection 스키마에 대한 모델 파일 내에 `createdTime` 속성 추가
- `user_infos` collection 스키마에 대한 모델 **swagger-doc** definition 수정
- `회원가입` API에 대한 **swagger-doc** http response 내에 createdTime 속성 추가
- 수정 전 `user_infos` collection 스키마 모델 구조
- 수정 후 `user_infos` collection 스키마 모델 구조
> **createdTime** 속성이 추가됨
=> [FIX] `user_infos collection` 스키마 내에 `createdTime` 속성 추가 #115

package-lock.json, package.json, routes/auth.js
resolve #117 
기존 서버 프로젝트 내에 설치되어 있던 `swagger-ui-express` 패키지 `4.6.3` 버전에서
`5.0.0` 버전으로 업데이트 하였습니다.
- `swagger-ui-express` 버전 `4.6.3` ➜ **`5.0.0`** 으로 업데이트
- `회원 탈퇴 및 사유 기록` API `400` 에러 확인에 대한 조건문 참 조건 수행문 **소괄호** 제거 및 `swagger-doc` 내용 추가
없습니다
=> [fix]: swagger-ui-express 패키지 버전 업데이트 (#117)

routes/auth.js, routes/bookmarks.js, routes/headcounts.js, routes/places.js, routes/users.js
resolve #119 
프로젝트 내에 `swagger-doc` **definition**으로 정의된 부분을
**`HTTP response body`** 로써 사용하는 APIs에 대하여 해당
definition으로 변경하여 코드의 길이를 축소하였습니다.
- `auth` 라우터 내 **회원 가입** API `swagger-doc` 리팩토링
- `bookmarks` 라우터 내 **신규 즐겨찾기 리스트 등록** API `swagger-doc` 리팩토링
- `headcounts` 라우터 내 **특정 장소에 대한 인원수 등록** API `swagger-doc` 리팩토링
- `places` 라우터 내 **신규 장소 등록** API `swagger-doc` 리팩토링
- `users` 라우터 내 **임시 비밀번호 생성** API `swagger-doc` 리팩토링
없습니다
=> [refactor]: 일부 APIs swagger-doc 리펙토링 (#119)
